#! /bin/bash
echo "read aliasrc"

# スクリプトフォルダをfzfで検索しエディタで開く
se(){
  du -a ~/.scripts/* | \
  awk '{
    if ($2 !~ /(stashdir|testdir|tags)/){
      print $2
    }
  }' | \
  fzf | \
  xargs -r $EDITOR ;
}

# スクリプトフォルダをfzfで検索し実行
es(){
  du -a ~/.scripts/* | \
  awk '{
    if ($2 !~ /(stashdir|testdir|tags)/){
      print $2
    }
  }' | \
  fzf | \
  xargs -rI {} bash -ci "{}";
}

# カレントディレクトリ配下をfzf検索しエディタで開く
nf(){
  fzf | \
  xargs -r -I % $EDITOR % ;
}

# Manページをvimで開く
nam(){  eval "nv -c \"Man $1 | only\"" ; }
# チートシートを検索
ccs(){
  if [ $# -eq 1 ]; then
    curl "https://cheat.sh/$1" ;
  elif [ $# -eq 2 ]; then
    curl "https://cheat.sh/$1/$2" ;
  fi
}
cv() {
  local current_path=$(pwd)
  local root_path="/"
  local paths=()

  # ルートディレクトリから現在地までのパスを段階的に取得
  while [[ "$current_path" != "$root_path" ]]; do
    paths+=("$current_path")
    current_path=$(dirname "$current_path")
  done

  # パスを逆順にして fzf に渡し、選択されたパスに移動
  local selected_path=$(printf '%s\n' "${paths[@]}" | fzf)

  if [[ -n "$selected_path" ]]; then
    cd "$selected_path"
  fi
}

wtr(){
  if [ $# -eq 0 ]; then
    curl wttr.in/Katsushika
  else
    curl wttr.in/$1
  fi
}
